import { FunctionComponent } from "react";

export interface IIconProps {
    className?: string;
    height?: number;
    width?: number;
    "data-selenium"?: string;
    title?: string;
}

interface ISvgProps {
    className?: string;
    name: string;
    icon: string;
    height?: number;
    width?: number;
    "data-selenium"?: string;
    title?: string;
    strokeWidth?: number;
}

export const Svg: FunctionComponent<ISvgProps> = ({
    className = "",
    name,
    icon,
    height = 16,
    width = 16,
    title,
    strokeWidth,
    "data-selenium": dataSelenium,
}) => {
    return (
        <svg
            className={`bhIcon ${className}`}
            height={height}
            width={width}
            data-selenium={dataSelenium}
            strokeWidth={strokeWidth}
        >
            {title && <title>{title}</title>}
            <use name={name} href={icon} />
        </svg>
    );
};
// dunno, work out

/*

/**
 * DO NOT EDIT THIS FILE
 * This file was auto generated
 *
 * see docs/common/Icons.md
 

import { FunctionComponent } from "react";

import { IIconProps, Svg } from "src/client/App/common/Icons/Svg";

export const AllIcon: FunctionComponent<IIconProps> = props => {
    const icon = `<symbol id="AllIcon" fill="none" stroke="none" viewBox="0 0 48 48"><path fill="currentColor" d="M22 8H9c-.55 0-1 .45-1 1v13c0 .55.45 1 1 1h13c.55 0 1-.45 1-1V9c0-.55-.45-1-1-1m-1 13H10V10h11zM39 8H26c-.55 0-1 .45-1 1v13c0 .55.45 1 1 1h13c.55 0 1-.45 1-1V9c0-.55-.45-1-1-1m-1 13H27V10h11zm-16 4H9c-.55 0-1 .45-1 1v13c0 .55.45 1 1 1h13c.55 0 1-.45 1-1V26c0-.55-.45-1-1-1m-1 13H10V27h11zm18-13H26c-.55 0-1 .45-1 1v13c0 .55.45 1 1 1h13c.55 0 1-.45 1-1V26c0-.55-.45-1-1-1m-1 13H27V27h11z"/></symbol>`;

    return <Svg name="AllIcon" icon={icon} {...props} />;
};
*/
